//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostolo.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBank")]
    public interface IBank {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/Bejelentkezes", ReplyAction="http://tempuri.org/IBank/BejelentkezesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.Hiba), Action="http://tempuri.org/IBank/BejelentkezesHibaFault", Name="Hiba", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string Bejelentkezes(string uname, string passwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/Bejelentkezes", ReplyAction="http://tempuri.org/IBank/BejelentkezesResponse")]
        System.Threading.Tasks.Task<string> BejelentkezesAsync(string uname, string passwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/Kijelentkezes", ReplyAction="http://tempuri.org/IBank/KijelentkezesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.Hiba), Action="http://tempuri.org/IBank/KijelentkezesHibaFault", Name="Hiba", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string Kijelentkezes(string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/Kijelentkezes", ReplyAction="http://tempuri.org/IBank/KijelentkezesResponse")]
        System.Threading.Tasks.Task<string> KijelentkezesAsync(string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/Feltoltes", ReplyAction="http://tempuri.org/IBank/FeltoltesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.Hiba), Action="http://tempuri.org/IBank/FeltoltesHibaFault", Name="Hiba", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string Feltoltes(int osszeg, string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/Feltoltes", ReplyAction="http://tempuri.org/IBank/FeltoltesResponse")]
        System.Threading.Tasks.Task<string> FeltoltesAsync(int osszeg, string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/Lekerdezes", ReplyAction="http://tempuri.org/IBank/LekerdezesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.Hiba), Action="http://tempuri.org/IBank/LekerdezesHibaFault", Name="Hiba", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        string Lekerdezes(string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/Lekerdezes", ReplyAction="http://tempuri.org/IBank/LekerdezesResponse")]
        System.Threading.Tasks.Task<string> LekerdezesAsync(string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/Utalas", ReplyAction="http://tempuri.org/IBank/UtalasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.Hiba), Action="http://tempuri.org/IBank/UtalasHibaFault", Name="Hiba", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        WcfService.Utal Utalas(string felhnev, int osszeg, string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/Utalas", ReplyAction="http://tempuri.org/IBank/UtalasResponse")]
        System.Threading.Tasks.Task<WcfService.Utal> UtalasAsync(string felhnev, int osszeg, string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/UtalasokList", ReplyAction="http://tempuri.org/IBank/UtalasokListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfService.Hiba), Action="http://tempuri.org/IBank/UtalasokListHibaFault", Name="Hiba", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        WcfService.Utalasok[] UtalasokList(string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBank/UtalasokList", ReplyAction="http://tempuri.org/IBank/UtalasokListResponse")]
        System.Threading.Tasks.Task<WcfService.Utalasok[]> UtalasokListAsync(string uid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankChannel : Hostolo.ServiceReference1.IBank, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankClient : System.ServiceModel.ClientBase<Hostolo.ServiceReference1.IBank>, Hostolo.ServiceReference1.IBank {
        
        public BankClient() {
        }
        
        public BankClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Bejelentkezes(string uname, string passwd) {
            return base.Channel.Bejelentkezes(uname, passwd);
        }
        
        public System.Threading.Tasks.Task<string> BejelentkezesAsync(string uname, string passwd) {
            return base.Channel.BejelentkezesAsync(uname, passwd);
        }
        
        public string Kijelentkezes(string uid) {
            return base.Channel.Kijelentkezes(uid);
        }
        
        public System.Threading.Tasks.Task<string> KijelentkezesAsync(string uid) {
            return base.Channel.KijelentkezesAsync(uid);
        }
        
        public string Feltoltes(int osszeg, string uid) {
            return base.Channel.Feltoltes(osszeg, uid);
        }
        
        public System.Threading.Tasks.Task<string> FeltoltesAsync(int osszeg, string uid) {
            return base.Channel.FeltoltesAsync(osszeg, uid);
        }
        
        public string Lekerdezes(string uid) {
            return base.Channel.Lekerdezes(uid);
        }
        
        public System.Threading.Tasks.Task<string> LekerdezesAsync(string uid) {
            return base.Channel.LekerdezesAsync(uid);
        }
        
        public WcfService.Utal Utalas(string felhnev, int osszeg, string uid) {
            return base.Channel.Utalas(felhnev, osszeg, uid);
        }
        
        public System.Threading.Tasks.Task<WcfService.Utal> UtalasAsync(string felhnev, int osszeg, string uid) {
            return base.Channel.UtalasAsync(felhnev, osszeg, uid);
        }
        
        public WcfService.Utalasok[] UtalasokList(string uid) {
            return base.Channel.UtalasokList(uid);
        }
        
        public System.Threading.Tasks.Task<WcfService.Utalasok[]> UtalasokListAsync(string uid) {
            return base.Channel.UtalasokListAsync(uid);
        }
    }
}
